# Canvas settings.
canvas:
  prefix: "https://canvas.instructure.com"
  course: "1278337"

# Exclude the following files/folders from processing. Jekyll currently gives
# exclude precedence over include, so list files not to be included here.
exclude:
  - CHANGELOG.md
  - LICENSE
  - files
  - lib                            # the following lines are not for production
  - spec                           # ...
  - Gemfile                        # ...
  - Gemfile.lock                   # ...
  - canvas-workflow-jekyll.gemspec # ...
  - canvas-workflow-jekyll-*.gem   # ...
  - vendor                         # ...
