# Canvas settings
canvas:
  prefix: "https://canvas.instructure.com"
  course: "1278337"

# Exclude the following files from processing. Jekyll currently gives exclude
# precedence over include, so list files not to be included here
exclude:
  - CHANGELOG.md
  - LICENSE
  - files
  - jekyll-canvas-yaml.gemspec

################################################################################
####################   DO NOT CHANGE ANYTHING BELOW HERE!   ####################
################################################################################

# Use the Jekyll Canvas Yaml theme to produce correctly formatted yaml files for
# the Canvas LMS API.
theme: jekyll-canvas-yaml

# Disable any plugins that are not explicitly enabled (whitelisted) below
safe: true
# Use the Jekyll Canvas tags set of plugins to provide useful tags for the
# Canvas LMS.
whitelist:
  - jekyll-canvas-tags
plugins:
  - jekyll-canvas-tags

# Render pages, even those marked unpublished
unpublished: true

# Disable syntax highlighting
highlighter: none

# Fail build if there is incorrect yaml front matter
strict_front_matter: true

# Set the default layouts for certain groups of files
defaults:
  - scope:
      path: "README.md"
    values:
      layout: syllabus
  - scope:
      path: "assignments"
    values:
      layout: assignment
  - scope:
      path: "pages"
    values:
      layout: page
