safe: true
strict_front_matter: true

# Build settings
highlighter: none

# Render pages, even those marked unpublished
unpublished: true

# Use the Jekyll Canvas Yaml theme to produce correctly formatted yaml files for
# the Canvas LMS API. (Commented out because this is the jekyll-canvas-yaml
# theme)
# theme: jekyll-canvas-yaml

# Use the Jekyll Canvas tags set of plugins to provide useful tags for the
# Canvas LMS.
whitelist:
  - jekyll-canvas-tags
plugins:
  - jekyll-canvas-tags

# Exclude from processing. Jekyll gives currently gives exclude precedence over
# include, so list files not to be included here
exclude:
  - CHANGELOG.md
  - LICENSE
  - files
  - jekyll-canvas-yaml-*.gem
  - jekyll-canvas-yaml.gemspec

defaults:
  -
    scope:
      path: "README.md"
    values:
      layout: syllabus
  -
    scope:
      path: "pages"
    values:
      layout: page
