# Tell Travis the project language.
language: ruby

# Route to the container-based infrastructure for a faster build.
sudo: false

# Install the required Ruby Gems --- this location is preferred over a Gemfile,
# so that repo does not require an additional config file.
install:
  - gem install 'canvas-workflow-jekyll' -v '= 0.3.0'
  - gem install 'canvas-workflow-travis' -v '= 0.9.0'

# The stages of building and deploying the Canvas Workflow site.
jobs:
  include:
    - # push files to canvas
      stage: push files
      script: canvas sync
    - # build and deploy site
      stage: build and deploy site
      script:
        # build site
        - jekyll build --verbose ; EXITCODE=$? ; (exit $EXITCODE)
        # deploy site to Canvas
        - test $EXITCODE -eq 0 && canvas deploy
