# Canvas settings.
canvas:
  prefix: "https://example.instructure.com"
  course: "12345"

# Exclude the following files/folders from processing. Jekyll currently gives
# exclude precedence over include, so list files/folder not to be included here.
exclude:
  - files
